-- These used to be defined in subterrane, but now dfcaverns handles it.
if not minetest.registered_nodes["subterrane:wet_flowstone"] then
	minetest.register_alias("subterrane:dry_stal_1", "df_mapitems:dry_stal_1")
	minetest.register_alias("subterrane:dry_stal_2", "df_mapitems:dry_stal_2")
	minetest.register_alias("subterrane:dry_stal_3", "df_mapitems:dry_stal_3")
	minetest.register_alias("subterrane:dry_stal_4", "df_mapitems:dry_stal_4")
	minetest.register_alias("subterrane:wet_stal_1", "df_mapitems:wet_stal_1")
	minetest.register_alias("subterrane:wet_stal_2", "df_mapitems:wet_stal_2")
	minetest.register_alias("subterrane:wet_stal_3", "df_mapitems:wet_stal_3")
	minetest.register_alias("subterrane:wet_stal_4", "df_mapitems:wet_stal_4")
	minetest.register_alias("subterrane:wet_flowstone", "df_mapitems:wet_flowstone")
	minetest.register_alias("subterrane:dry_flowstone", "df_mapitems:dry_flowstone")
end

minetest.register_alias("dfcaverns:cave_coral_3"                 , "df_mapitems:cave_coral_3"                 )
minetest.register_alias("dfcaverns:cave_coral_2"                 , "df_mapitems:cave_coral_2"                 )
minetest.register_alias("dfcaverns:cave_coral_1"                 , "df_mapitems:cave_coral_1"                 )
minetest.register_alias("dfcaverns:dry_stal_1"                   , "df_mapitems:dry_stal_1"                   )
minetest.register_alias("dfcaverns:dry_stal_2"                   , "df_mapitems:dry_stal_2"                   )
minetest.register_alias("dfcaverns:dry_stal_3"                   , "df_mapitems:dry_stal_3"                   )
minetest.register_alias("dfcaverns:dry_stal_4"                   , "df_mapitems:dry_stal_4"                   )
minetest.register_alias("dfcaverns:wet_stal_1"                   , "df_mapitems:wet_stal_1"                   )
minetest.register_alias("dfcaverns:wet_stal_2"                   , "df_mapitems:wet_stal_2"                   )
minetest.register_alias("dfcaverns:wet_stal_3"                   , "df_mapitems:wet_stal_3"                   )
minetest.register_alias("dfcaverns:wet_stal_4"                   , "df_mapitems:wet_stal_4"                   )
minetest.register_alias("dfcaverns:wet_flowstone"                , "df_mapitems:wet_flowstone"                )
minetest.register_alias("dfcaverns:dry_flowstone"                , "df_mapitems:dry_flowstone"                )
minetest.register_alias("dfcaverns:icicle_1"                     , "df_mapitems:icicle_1"                     )
minetest.register_alias("dfcaverns:icicle_2"                     , "df_mapitems:icicle_2"                     )
minetest.register_alias("dfcaverns:icicle_3"                     , "df_mapitems:icicle_3"                     )
minetest.register_alias("dfcaverns:icicle_4"                     , "df_mapitems:icicle_4"                     )
minetest.register_alias("dfcaverns:glow_mese"                    , "df_mapitems:glow_mese"                    )
minetest.register_alias("dfcaverns:glow_ruby_ore"                , "df_mapitems:glow_ruby_ore"                )
minetest.register_alias("dfcaverns:big_crystal"                  , "df_mapitems:big_crystal"                  )
minetest.register_alias("dfcaverns:med_crystal"                  , "df_mapitems:med_crystal"                  )
minetest.register_alias("dfcaverns:big_crystal_30"               , "df_mapitems:big_crystal_30"               )
minetest.register_alias("dfcaverns:med_crystal_30"               , "df_mapitems:med_crystal_30"               )
minetest.register_alias("dfcaverns:big_crystal_30_45"            , "df_mapitems:big_crystal_30_45"            )
minetest.register_alias("dfcaverns:med_crystal_30_45"            , "df_mapitems:med_crystal_30_45"            )
minetest.register_alias("dfcaverns:glow_worm"                    , "df_mapitems:glow_worm"                    )
minetest.register_alias("dfcaverns:dirt_with_cave_moss"          , "df_mapitems:dirt_with_cave_moss"          )
minetest.register_alias("dfcaverns:cobble_with_floor_fungus"     , "df_mapitems:cobble_with_floor_fungus"     )
minetest.register_alias("dfcaverns:cobble_with_floor_fungus_fine", "df_mapitems:cobble_with_floor_fungus_fine")
minetest.register_alias("dfcaverns:snareweed"                    , "df_mapitems:snareweed"                    )