laptop.register_theme("Argyle", {
	desktop_background = "laptop_theme_argyle_desktop_background.png",
	app_background = "laptop_theme_argyle_app_background.png",
	major_button = "laptop_theme_argyle_major_button.png",
	minor_button = "laptop_theme_argyle_major_button.png",
	back_button = "laptop_theme_argyle_exit_button.png",
	back_textcolor= "#000000",
	exit_button = "blank.png",
	desktop_icon_button = "blank.png",
	exit_button = "laptop_theme_argyle_exit_button.png",
	exit_textcolor = "#000000",
	desktop_icon_label_textcolor = "#000000",
	desktop_icon_label_button = "laptop_theme_desktop_icon_label_button_grey.png",
	os_max_version = '6.99',
})
