laptop.register_theme("Boing!", {
	desktop_background = "laptop_theme_boing_desktop_background.png",
	app_background = "laptop_theme_boing_app_background.png",
	major_button = "laptop_theme_boing_major_button.png",
	major_textcolor = "#FFFFFF",
	minor_button = "laptop_theme_snowpines_minor_button.png",
	minor_textcolor = "#FFFFFF",
	back_button = "laptop_theme_boing_back_button.png",	
	back_textcolor = "#000000",
	exit_button = "laptop_theme_boing_exit_button.png",
	exit_character = " ",
	desktop_icon_button = "blank.png",
	taskbar_clock_position_and_size = "11,-.25;4,0.4",
	desktop_icon_label_button = "laptop_theme_boing_major_button.png",
	titlebar_textcolor = "#000000",
	os_max_version = '7.99',
})
