-- Table that holds the items that the lootchests can contain.

	-- Items for the Red Christmas Chest. -- Anywhere
	lootchests.loot_table["christmas_holiday_pack:chest_red"] = {
	    {"christmas_holiday_pack:helmet_cane",},
	    {"christmas_holiday_pack:suit_tree", 1},
	    {"christmas_holiday_pack:shirt_ugly_sweater", 1},
	    {"christmas_holiday_pack:mask_santa_hat", 1},
	    {"christmas_holiday_pack:candy_cane", 8},
	    {"christmas_holiday_pack:peppermint_candies", 4},
	    {"christmas_holiday_pack:green_peppermint_candies", 1},
	    {"christmas_holiday_pack:gingerbread_cookie", 1},
	    {"christmas_holiday_pack:sugar_cookie", 1},
	    {"christmas_holiday_pack:sugar_cookie_bell", 1},
	    {"christmas_holiday_pack:sugar_cookie_star", 1},
	    {"christmas_holiday_pack:sugar_cookie_tree", 1},
	    {"christmas_holiday_pack:eggnog_glass", 1},
	    {"christmas_holiday_pack:peppermint_seeds", 1},
	    {"christmas_holiday_pack:ginger", 1},
	    {"christmas_holiday_pack:candy_cane_block", 1},
	    {"christmas_holiday_pack:green_candy_cane_block", 1},
	    {"christmas_holiday_pack:gingerbread_block", 1},
	    {"christmas_holiday_pack:frosting_block", 1},
	    {"christmas_holiday_pack:mistletoe", 1},
	    {"christmas_holiday_pack:reef", 1},
	    {"christmas_holiday_pack:icicles", 2},
	    {"christmas_holiday_pack:christmas_star", 1},
	    {"christmas_holiday_pack:garland", 4},
	    {"christmas_holiday_pack:festive_garland", 2},
	    {"christmas_holiday_pack:festive_garland_lights", 4},
	    {"christmas_holiday_pack:garland_red", 4},
	    {"christmas_holiday_pack:garland_yellow", 4},
	    {"christmas_holiday_pack:garland_white", 4},
	    {"christmas_holiday_pack:ornament_white", 4},
	    {"christmas_holiday_pack:ornament_yellow", 4},
	    {"christmas_holiday_pack:ornament_red", 4},
	    {"christmas_holiday_pack:ornament_green", 4},
	    {"christmas_holiday_pack:ornament_blue", 4},
	    {"christmas_holiday_pack:ornament_orange", 4},
	    {"christmas_holiday_pack:ornament_purple", 4},
	    {"christmas_holiday_pack:ornament_pink", 4},
	    {"christmas_holiday_pack:painting_02", 1},
	    {"christmas_holiday_pack:candy_cane_pickaxe", 1},
	    {"christmas_holiday_pack:candy_cane_axe", 1},
	    {"gramophone:vinyl_disc10",1},
	}

	-- Items for the Green Christmas Chest. -- Underground
	lootchests.loot_table["christmas_holiday_pack:chest_green"] = {
	    {"default:stick", 16},
  	    {"christmas_holiday_pack:leggings_cane", },
	    {"mask_green_santa_hat", 1},
	    {"christmas_holiday_pack:chestplate_cane", },
	    {"christmas_holiday_pack:boots_cane", 1},
	    {"christmas_holiday_pack:green_candy_cane", 8},
	    {"christmas_holiday_pack:gingerbread", 2},
	    {"christmas_holiday_pack:green_peppermint_candies", 2},
	    {"christmas_holiday_pack:gingerbread_cookie", 1},
	    {"christmas_holiday_pack:sugar_cookie", 4},
	    {"christmas_holiday_pack:suit_santa", 1},
	    {"christmas_holiday_pack:sugar_cookie_bell", 2},
	    {"christmas_holiday_pack:sugar_cookie_star", 2},
	    {"christmas_holiday_pack:sugar_cookie_tree", 1},
	    {"christmas_holiday_pack:eggnog_glass", 2},
	    {"christmas_holiday_pack:peppermint_seeds", 2},
	    {"christmas_holiday_pack:ginger", 1},
	    {"christmas_holiday_pack:candy_cane_block", 2},
	    {"christmas_holiday_pack:green_candy_cane_block", 1},
	    {"christmas_holiday_pack:gingerbread_block", 1},
	    {"christmas_holiday_pack:frosting_block", 2},
	    {"christmas_holiday_pack:mistletoe", 1},
	    {"christmas_holiday_pack:reef", 1},
	    {"christmas_holiday_pack:icicles", 4},
	    {"christmas_holiday_pack:christmas_star", 1},
	    {"christmas_holiday_pack:garland", 4},
	    {"christmas_holiday_pack:festive_garland", 2},
	    {"christmas_holiday_pack:festive_garland_lights", 2},
	    {"christmas_holiday_pack:garland_red", 4},
	    {"christmas_holiday_pack:garland_yellow", 4},
	    {"christmas_holiday_pack:garland_white", 4},
	    {"christmas_holiday_pack:ornament_white", 4},
	    {"christmas_holiday_pack:ornament_yellow", 4},
	    {"christmas_holiday_pack:ornament_red", 4},
	    {"christmas_holiday_pack:ornament_green", 4},
	    {"christmas_holiday_pack:ornament_blue", 4},
	    {"christmas_holiday_pack:ornament_orange", 4},
	    {"christmas_holiday_pack:ornament_purple", 4},
	    {"christmas_holiday_pack:ornament_pink", 4},
	    {"christmas_holiday_pack:painting_01", 1},
	    {"christmas_holiday_pack:painting_02", 1},
	    {"christmas_holiday_pack:stocking", 1},
	    {"christmas_holiday_pack:candy_cane_pickaxe", 1},
	    {"christmas_holiday_pack:candy_cane_axe", 1},
	}

	-- Items for the Blue Christmas Chest. -- Icy Places
	lootchests.loot_table["christmas_holiday_pack:chest_blue"] = {
	    {"default:stick", 16},
	    {"christmas_holiday_pack:christmas_bell", 1},
	    {"christmas_holiday_pack:shield_cane", 1},
	    {"christmas_holiday_pack:boots_cane", 1},
	    {"christmas_holiday_pack:leggings_cane", 1},
	    {"christmas_holiday_pack:suit_orange_parka", 1},
	    {"christmas_holiday_pack:mask_red_poof_ball_hat", 1},
	    {"christmas_holiday_pack:gingerbread", 2},
	    {"christmas_holiday_pack:peppermint_candies", 4},
	    {"christmas_holiday_pack:green_peppermint_candies", 4},
	    {"christmas_holiday_pack:gingerbread_cookie", 1},
	    {"christmas_holiday_pack:sugar_cookie", 4},
	    {"christmas_holiday_pack:sugar_cookie_bell", 2},
	    {"christmas_holiday_pack:sugar_cookie_star", 2},
	    {"christmas_holiday_pack:sugar_cookie_tree", 1},
	    {"christmas_holiday_pack:eggnog_glass", 2},
	    {"christmas_holiday_pack:hot_chocolate_glass", 2},
	    {"christmas_holiday_pack:peppermint_seeds", 4},
	    {"christmas_holiday_pack:ginger", 4},
	    {"christmas_holiday_pack:candy_cane_block", 2},
	    {"christmas_holiday_pack:green_candy_cane_block", 1},
	    {"christmas_holiday_pack:gingerbread_block", 2},
	    {"christmas_holiday_pack:frosting_block", 4},
	    {"christmas_holiday_pack:mistletoe", 1},
	    {"christmas_holiday_pack:reef", 1},
	    {"christmas_holiday_pack:icicles", 4},
	    {"christmas_holiday_pack:christmas_star", 1},
	    {"christmas_holiday_pack:garland", 4},
	    {"christmas_holiday_pack:festive_garland", 2},
	    {"christmas_holiday_pack:festive_garland_lights", 4},
	    {"christmas_holiday_pack:garland_red", 4},
	    {"christmas_holiday_pack:garland_yellow", 4},
	    {"christmas_holiday_pack:garland_white", 4},
	    {"christmas_holiday_pack:ornament_white", 1},
	    {"christmas_holiday_pack:ornament_yellow", 4},
	    {"christmas_holiday_pack:ornament_red", 4},
	    {"christmas_holiday_pack:ornament_green", 4},
	    {"christmas_holiday_pack:ornament_blue", 4},
	    {"christmas_holiday_pack:ornament_orange", 4},
	    {"christmas_holiday_pack:ornament_purple", 4},
	    {"christmas_holiday_pack:ornament_pink", 4},
	    {"christmas_holiday_pack:painting_01", 1},
	    {"christmas_holiday_pack:painting_02", 1},
	    {"christmas_holiday_pack:painting_03", 1},
	    {"christmas_holiday_pack:painting_04", 1},
	    {"christmas_holiday_pack:stocking", 1},
	    {"christmas_holiday_pack:green_stocking", 1},
	    {"christmas_holiday_pack:candy_cane_pickaxe", 1},
	    {"christmas_holiday_pack:candy_cane_axe", 1},
	    {"christmas_holiday_pack:candy_cane_sword", 1},
	    {"gramophone:vinyl_disc10",1},
	    {"gramophone:vinyl_disc11",1},
	}

	-- Items for the Yellow Christmas Chest. -- In stone underground
	lootchests.loot_table["christmas_holiday_pack:chest_yellow"] = {
	    {"default:stick", 16},
	    {"christmas_holiday_pack:christmas_bell", 1},
	    {"christmas_holiday_pack:leggings_cane", 1},
	    {"christmas_holiday_pack:shield_cane", 1},
	    {"christmas_holiday_pack:boots_cane", 1},
	    {"christmas_holiday_pack:chestplate_cane", 1},
	    {"christmas_holiday_pack:suit_elf", 1},
	    {"christmas_holiday_pack:gingerbread", 4},
	    {"christmas_holiday_pack:gingerbread_cookie", 2},
	    {"christmas_holiday_pack:sugar_cookie_bell", 2},
	    {"christmas_holiday_pack:sugar_cookie_star", 2},
	    {"christmas_holiday_pack:sugar_cookie_tree", 1},
	    {"christmas_holiday_pack:eggnog_glass", 4},
	    {"christmas_holiday_pack:hot_chocolate_glass", 4},
	    {"christmas_holiday_pack:peppermint_seeds", 8},
	    {"christmas_holiday_pack:ginger", 8},
	    {"christmas_holiday_pack:candy_cane_block", 8},
	    {"christmas_holiday_pack:green_candy_cane_block", 2},
	    {"christmas_holiday_pack:gingerbread_block", 4},
	    {"christmas_holiday_pack:frosting_block", 4},
	    {"christmas_holiday_pack:mistletoe", 2},
	    {"christmas_holiday_pack:reef", 2},
	    {"christmas_holiday_pack:icicles", 8},
	    {"christmas_holiday_pack:christmas_star", 2},
	    {"christmas_holiday_pack:garland", 8},
	    {"christmas_holiday_pack:festive_garland", 4},
	    {"christmas_holiday_pack:festive_garland_lights", 8},
	    {"christmas_holiday_pack:garland_red", 4},
	    {"christmas_holiday_pack:garland_yellow", 4},
	    {"christmas_holiday_pack:garland_white", 8},
	    {"christmas_holiday_pack:ornament_white", 8},
	    {"christmas_holiday_pack:ornament_yellow", 8},
	    {"christmas_holiday_pack:ornament_red", 8},
	    {"christmas_holiday_pack:ornament_green", 8},
	    {"christmas_holiday_pack:ornament_blue", 8},
	    {"christmas_holiday_pack:ornament_orange", 8},
	    {"christmas_holiday_pack:ornament_purple", 8},
	    {"christmas_holiday_pack:ornament_pink", 8},
	    {"christmas_holiday_pack:painting_01", 1},
	    {"christmas_holiday_pack:painting_02", 1},
	    {"christmas_holiday_pack:painting_03", 1},
	    {"christmas_holiday_pack:painting_04", 1},
	    {"christmas_holiday_pack:painting_05", 1},
	    {"christmas_holiday_pack:painting_06", 1},
	    {"christmas_holiday_pack:stocking", 4},
	    {"christmas_holiday_pack:green_stocking", 4},
	    {"christmas_holiday_pack:candy_cane_pickaxe", 1},
	    {"christmas_holiday_pack:candy_cane_axe", 1},
	    {"christmas_holiday_pack:candy_cane_sword", 1},
	    {"gramophone:vinyl_disc10",1},
	    {"gramophone:vinyl_disc11",1},
	    {"gramophone:vinyl_disc12",1},
	    {"gramophone:vinyl_disc13",1},
	}


